name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23lipwxUDHjPOs5OvW"
GITHUB_OWNER = "FnICeN"
GITHUB_REPO = "NavSphere-data"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.fnicen.top/api/auth"
NEXT_PUBLIC_API_URL="https://nav.fnicen.top"

